# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e376883d5dc0d255db25ddeafae856f76464e93146c85e9aab2c85f8954adcd24cd04f4c43dcec547515ae59e21a8778515de130fc3a2703066aabf1471561dd

test:
  secret_key_base: 9ba885bbd833f6fae32c6470afa396dc9f643d31be680bc2384a78fc31b1b0ac00e84c09aef30d42318ce4cea3e8772f80d39fe73bb25ea1debf30f580acc0be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
